# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "buSnRsUElMkRYsvhB7z5icV4+1RTgPQfZA4AWUo97ljZ1FwmUBLpG0TxwaUfLBDShOy4s9A6/qN70E0zHCftxy6uRnXEz1QP7HYZ44Ap0iwAI+Rbu62cz4ZyZJMAnhw2DGrK9SvhwuW7Mp5llkFd5D+MAhqjlLZJLzdN49EY6vUQjsnMTMOGjhrorJWkKU9HdrD3tsy5U0suppsUatvbY0KPDr+fGzYQVdjOjGrEuEurkEasmqxQlA6M0P7mHVfQQ7ad/lr7VFy/ZH8N3VBtAKUej1T5RzGbuW1aIxiyTca08Oxcm+2yFRUuwV7sr8tVYOTcDFsJl4qJ2ZnTBXge3FV8XGtuOkzRq1ALeRHKgwMO5i9Rp9hu3AmtddflQa5ndhlO8D013WDyCEEMq1YYv8KAxdn/qRP2dn4Foe/2I4qIOq6ktp+0uB0d7O16a2DY/Ah/qZ6nhQu2R9QbiQesv5QTAu84mVtVotWji/P25I3gKF7mCWFFooATblz6pC3sAVx1P4v5V0uefYFNkkTYxh567yxVLx2PKkQmbZsY/pa7AH1cA7TmSFo81oMWIGq0zWD9n1/je3BQzAUBGhjg65i1P0Pk37yFxRXA4K+B53C9Y8yOl8SoPU126NHubBxKJEk+zPBWVy/3y5tNW27lhy1z/Y9SB8s4zCFLIZMCeUg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml