appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: buSnRsUElMkRYsvhB7z5icV4+1RTgPQfZA4AWUo97ljZ1FwmUBLpG0TxwaUfLBDShOy4s9A6/qN70E0zHCftxy6uRnXEz1QP7HYZ44Ap0iwAI+Rbu62cz4ZyZJMAnhw2DGrK9SvhwuW7Mp5llkFd5D+MAhqjlLZJLzdN49EY6vUQjsnMTMOGjhrorJWkKU9HdrD3tsy5U0suppsUatvbY0KPDr+fGzYQVdjOjGrEuEurkEasmqxQlA6M0P7mHVfQQ7ad/lr7VFy/ZH8N3VBtAKUej1T5RzGbuW1aIxiyTca08Oxcm+2yFRUuwV7sr8tVYOTcDFsJl4qJ2ZnTBXge3FV8XGtuOkzRq1ALeRHKgwMO5i9Rp9hu3AmtddflQa5ndhlO8D013WDyCEEMq1YYv8KAxdn/qRP2dn4Foe/2I4qIOq6ktp+0uB0d7O16a2DY/Ah/qZ6nhQu2R9QbiQesv5QTAu84mVtVotWji/P25I3gKF7mCWFFooATblz6pC3sAVx1P4v5V0uefYFNkkTYxh567yxVLx2PKkQmbZsY/pa7AH1cA7TmSFo81oMWIGq0zWD9n1/je3BQzAUBGhjg65i1P0Pk37yFxRXA4K+B53C9Y8yOl8SoPU126NHubBxKJEk+zPBWVy/3y5tNW27lhy1z/Y9SB8s4zCFLIZMCeUg=}
bot:
  automerge: true
