travis:
  secure:
    BINSTAR_TOKEN: lYj9qG3I0SapoTMc3vkkbrtYZiOmW18npaSVDjmEEzEkAUGhqFeTh/muOtzhppwl8bO54L14/ueIieA3PE/VBTQCvtoi/vrtkEps2dvE49l788BH4gyalZE5Yz59ge73wMs9dmFTdrojMkuybVM2I7vsBNq576R5Q9WUjSkQ05bCT3e8CNF3fCptR4adOGXSCxK8JBRxXwdt7oFgn7NIuI8FwLUssEeE5RFyBNwzwBr0MYdTc9XbzwIZwCM5XNjMY9qiLpzDekUCFtK0XMjkBZlGhkwDoWph5O/Q0Tefm2t0BwftcYETgaunFQ+W0GkG/Ilv69SScwvotjHIyTr2TvvHsc9Pf0tZAtp3REp3zpw+i8TAOMDG8pvRdsBNDlgrj4AsguiGyz/U4A8af+OdF46B8ymX+IiWX/wWjQJqGbnrNmmfGkjvvSI/RhlKXBvEGllNPeEzdQyLSpf2O6ddwu0rR7pWy5fMPxABl2Fh9ZweOe1CSNxXIlna3HsZHYnDd3Cx+v42+XRwHTGe3o2iicnqyfElJEO0tqIM7Uw01f5ACFQZF2mW/kcou9BPclVj1fZuvtzi6kfB/dJk1RjWe/D3Cj1PC0gqWeVItpmBrlpbtTs9wrjJT+la3cgB3VEOVqgQqjBjjtPkDTWVRxhQyElbGo2DYuol+URmEPjjfEk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
